#!/bin/bash

# del: delete unwanted files generated by tex compilation.
# for posix-extended regular expression,
# see: https://imliuda.com/post/16

find -regextype posix-extended \
  -regex ".*\.(log|aux|blg|nav|snm|out|toc|xdv|synctex.gz(\(busy\))?|fdb_latexmk)" \
  -printf "\"%p\"\n" \
| xargs rm -f
